### PR TITLE
Feature/user

### LINKED ISSUE #27: Create a user Login & Signup feature
**For sending an email/text to a user about the search/filtering of logs we need to first create a user model in the app**

I will create a user authentication feature in the webapp for users to signup and keep the data of their logs . @Aryamanz29 please assign me this issue .

### PR DESCRIPTION
**Pull request by Ashsenior**
# Related Issues or bug

- Create a **Login** & **Signup** form .

Fixes: #27

# Proposed Changes

- Created **Login** , **Signup** and **Verification** components and backend . Improved little bit of UI.

# Additional Info

- Anything related Issues

# Screenshots

|        Original         |        Updated         |
| :---------------------: | :--------------------: |
| **original screenshot** | **updated screenshot** |
Screenshot (66)
Screenshot (67)
Screenshot (68)](https://user-images.githubusercontent.com/49332381/158767306-e2a97dff-ee38-476b-a37f-d74a57cbcbc3.png)
om/49332381/158767284-1bc22b88-53b9-41cb-9820-38a949b7ff6a.png)

### CODE REVIEW

**Review by Aryamanz29 — COMMENTED** [review]
Hey @Ashsenior Nice work 👏

but I'm not able to `signup`: 
Could you confirm this from your end?

`at backend`
```bash
Forbidden: /api/create-user/
[17/Mar/2022 08:55:05] "POST /api/create-user/ HTTP/1.1" 403 58
```

Screenshot from 2022-03-17 14-25-09

**Comment by Ashsenior** [comment]
Thnx for the appreciation

I guess it's an error caused because i didn't add **csrf_token** . Try now 

And it is working totally fine in my desktop .

**Comment by Ashsenior** [comment]
Any problem ?? @Aryamanz29

**Comment by Ashsenior** [comment]
Hey @Aryamanz29 how do I solve the code formatting issue ?

**Comment by HemantSachdeva** [comment]
> Hey @Aryamanz29 how do I solve the code formatting issue ?

Download flake8 python library using pip and format the code, commit and push it.

**Comment by HemantSachdeva** [comment]
@Aryamanz29 Why do we have black and flake both checks? :thinking:

**Comment by Ashsenior** [comment]
> @Aryamanz29 Why do we have black and flake both checks? 🤔

Do i remove the black-check code ?

**Comment by HemantSachdeva** [comment]
> > @Aryamanz29 Why do we have black and flake both checks? thinking
> 
> Do i remove the black-check code ?

Amm your choice, it just focus on single/double quotes and formats a dictionary in a single line (awful imo). That's all what I've observed about the black linting.

**Comment by Ashsenior** [comment]
can you please merge it now ?
and please add the level3 and GSSoC22 tag because gssoc system doesnt recognizes it otherwise
@Aryamanz29

**Comment by Aryamanz29** [comment]
> can you please merge it now ? and please add the level3 and GSSoC22 tag because gssoc system doesnt recognizes it otherwise @Aryamanz29

I'm really sorry. I'm too busy with my other commitments. Last time I've reviewed your PR's it looks good to me, but I guess when running a search on logs after uploading it doesn't show me expected results. I'll test it again and let you know :+1:
Right now, I'm merging your work to `develop branch` and also added appropriate issue labels to  so that it will count towards your contribution :+1:

**Comment by Aryamanz29** [comment]
> @Aryamanz29 Why do we have black and flake both checks? thinking

We're using `Flake8` for ensuring code follows `PEP 8` standard & `Black` for code formatting.

**Comment by Aryamanz29** [comment]
@Ashsenior Thanks for your contribution 🎉 & @HemantSachdeva For helping him out :+1:

**Pull request merged**
