### PR TITLE
Dockerize the frontend app & the backend services

### LINKED ISSUE #22: Dockerize this project
- `Dockerize` this project
- Update `README.md` as per change

### PR DESCRIPTION
**Pull request by hazemessam**
# Related Issues or bug
Fixes: #22 

image

### CODE REVIEW

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
Great work @hazemessam 👏

**NOTE : Before start working on requested changes, I would highly recommend you to run this project locally and try to upload & search query on `sample-log file` present in root directory of the project.**

Some changes I would suggest before merging this one:
- I tested your PR and found that docker-compose missing `elasticsearch service` and it is essential for this project to run properly.

 **Some references that might help you** :point_down: 
1. https://tamerlan.dev/how-to-integrate-elasticsearch-with-drf/ 
2. https://dev.to/aymanemx/building-a-full-text-search-app-using-django-docker-and-elasticsearch-3bai
3. https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/docker-compose.yml
- Please update `CORS_ORIGIN_WHITELIST & ALLOWED HOSTS` as well because it's giving me 500 Internal server errors on console. 
https://github.com/Aryamanz29/Elastic-CFC/blob/c2a72f56d2b89a61ffec9c7b4a2805a98c5975e7/core/settings.py#L79-L82
https://github.com/Aryamanz29/Elastic-CFC/blob/c2a72f56d2b89a61ffec9c7b4a2805a98c5975e7/core/settings.py#L28
- Frontend also not working properly in docker,  It's unable to download frontend dependencies through `npm install` and also make sure you change `backend url` :point_down: 
https://github.com/Aryamanz29/Elastic-CFC/blob/c2a72f56d2b89a61ffec9c7b4a2805a98c5975e7/frontend/src/Components/Hero.js#L44

- It would be better if you could attach any kind of  `GIF/Video` in your PR to showcase your work 🙂

**Comment by hazemessam** [comment]
@Aryamanz29

**Comment by hazemessam** [comment]
@Aryamanz29 

When calling `POST /api/document`, `serializer.save()` throws this error `PermissionError(13, 'Permission denied')`

**Comment by hazemessam** [comment]
Please, note that we don't need to change the backend address from `localhost:8000` to `backend:8000` in the frontend, because the frontend will request the backend from the browser and the browser can access the backend container using `localhost`

**Comment by Aryamanz29** [comment]
> Please, note that we don't need to change the backend address from `localhost:8000` to `backend:8000` in the frontend, because the frontend will request the backend from the browser and the browser can access the backend container using `localhost`

You're right :+1:, It just mapped localhost address. We don't need to change that

**Review by Aryamanz29 — APPROVED** [review]
@hazemessam Great work, Thanks 👍👍

**Pull request merged**
